theme: jekyll-theme-minimal
title: ABAA Consulting Limited
description: Technical Business Consultancy
logo: /assets/images/logo.jpg # Placeholder for logo - Updated to JPG
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Services
    url: /services
  - title: Contact
    url: /contact
